#!/usr/bin/with-contenv bash

usermod -o -u "$NB_UID" "$NB_USER"

echo -e "\e[93m**** Running as UID:$NB_UID ****\e[38;5;241m"

chown -R "$NB_USER" "$HOME"
chown -R "$NB_USER" /notebooks
chown -R "$NB_USER" /codeserver
chown -R "$NB_USER" /src
chown -R "$NB_USER" /usr/local/lib/python3.9/dist-packages/zsh_jupyter_kernel/log
