#!/usr/bin/with-contenv bash

echo "### ENV ###"
env
echo "### ENV ###"


usermod -o -u "$NB_UID" "$USER"

echo -e "\e[93m**** Running as UID:$NB_UID ****\e[38;5;241m"

chown -R "$USER" "$HOME"
chown -R "$USER" /notebooks
chown -R "$USER" /codeserver
chown -R "$USER" /src
chown -R "$USER" /usr/local/lib/python3.9/dist-packages/zsh_jupyter_kernel/log
